# This is a config for E2B sandbox template.
# You can use template ID (c6dkvchptmn3mce2y11m) or template name (vibe-nextjs-project-krishna-3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-project-krishna-3") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-project-krishna-3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-project-krishna-3')

team_id = "d27097f5-7114-415a-99d5-6c1ededd64ee"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-project-krishna-3"
template_id = "c6dkvchptmn3mce2y11m"
